version: 2
updates:
  # Maintain dependencies for Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
