version: '3'

services:
  bot:
    build:
      context: .
    environment:
      - TELOXIDE_TOKEN=${TELEGRAM_BOT_TOKEN_TEST}
      - CHAT_GPT_API_TOKEN=gpt-token
      - DATABASE_URL=postgresql://docker:password@postgres:5432/postgres
      - REDIS_URL=redis://default:redispw@localhost:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
