# fly.toml file generated for telegram-rust-bot on 2022-11-20T18:55:49+01:00

app = "telegram-rust-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  RUST_LOG = "info"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
